COLUMN_INFO = [
    {'name': '_id', 'original': 'id'},
    {'name': 'ccf'},
    {'name': 'age', 'type': 'count'},
    {'name': 'sex', 'type': 'categorical'},
    {'name': 'pain location', 'type': 'categorical', 'original': 'painloc'},
    {'name': 'pain w exertion', 'type': 'boolean', 'original': 'painexer'},
    {'name': 'relieved after rest', 'type': 'boolean', 'original': 'relrest'},
    {'name': 'pncaden'},
    {'name': 'chest pain type', 'type': 'categorical', 'original': 'cp'},
    {'name': 'resting bp s', 'type': 'count', 'original': 'trestbps'},
    {'name': 'hypertension', 'type': 'boolean', 'original': 'htn'},
    {'name': 'cholesterol', 'type': 'count', 'original': 'chol'},
    {'name': 'smoker', 'type': 'boolean', 'original': 'smoke'},
    {'name': 'cigarettes per day'},
    {'name': 'years of smoking'},
    {'name': 'fasting blood sugar', 'type': 'boolean', 'original': 'fbs'},
    {'name': 'diabetes', 'type': 'boolean', 'original': 'dm'},
    {'name': 'family hist', 'type': 'boolean', 'original': 'famhist'},
    {'name': 'resting ecg', 'type': 'categorical', 'original': 'restecg'},
    {'name': 'ekg month'},
    {'name': 'ekg day'},
    {'name': 'ekg yr'},
    {'name': 'digitalis', 'type': 'boolean', 'original': 'dig'},
    {'name': 'beta blocker', 'type': 'boolean', 'original': 'prop'},
    {'name': 'nitrates', 'type': 'boolean', 'original': 'nitr'},
    {'name': 'calcium channel blocker', 'type': 'boolean', 'original': 'pro'},
    {'name': 'diuretic', 'type': 'boolean'},
    {'name': 'exercise protocol'},
    {'name': 'duration of exercise', 'type': 'real', 'original': 'thaldur'},
    {'name': 'thaltime'},
    {'name': 'mets achieved', 'type': 'count', 'original': 'met'},
    {'name': 'max heart rate', 'type': 'count', 'original': 'thalach'},
    {'name': 'resting heart rate', 'type': 'count', 'original': 'thalrest'},
    {'name': 'peak exercise bp 1', 'type': 'count', 'original': 'tpeakbps'},
    {'name': 'peak exercise bp 2', 'type': 'count', 'original': 'tpeakbpd'},
    {'name': 'dummy 1'},
    {'name': 'resting bp d', 'type': 'count', 'original': 'trestbpd'},
    {'name': 'exercise angina', 'type': 'boolean', 'original': 'exang'},
    {'name': 'xhypo'},
    {'name': 'oldpeak'},
    {'name': 'ST slope', 'type': 'categorical', 'original': 'slope'},
    {'name': 'ST height at rest', 'type': 'real', 'original': 'rldv5'},
    {'name': 'ST heaight at peak', 'type': 'real', 'original': 'rldv5e'},
    {'name': 'flouroscopy'},
    {'name': 'dummy 2'},
    {'name': 'dummy 3'},
    {'name': 'resting ejection fraction'},
    {'name': 'rest wall motion abnormality'},
    {'name': 'exercise ejection fraction'},
    {'name': 'exercsie wall motion'},
    {'name': 'thal'},
    {'name': 'dummy 4'},
    {'name': 'dummy 5'},
    {'name': 'dummy 6'},
    {'name': 'cath month'},
    {'name': 'cath day'},
    {'name': 'cath yr'},
    {'name': 'target', 'type': 'categorical', 'original': 'num'},
    {'name': 'lmt', 'type': 'categorical'},
    {'name': 'ladprox', 'type': 'categorical'},
    {'name': 'laddist', 'type': 'categorical'},
    {'name': 'diag', 'type': 'categorical'},
    {'name': 'cxmain', 'type': 'categorical'},
    {'name': 'ramus', 'type': 'categorical'},
    {'name': 'om1', 'type': 'categorical'},
    {'name': 'om2', 'type': 'categorical'},
    {'name': 'rcaprox', 'type': 'categorical'},
    {'name': 'rcadist', 'type': 'categorical'},
    {'name': 'dummy 7'},
    {'name': 'dummy 8'},
    {'name': 'dummy 9'},
    {'name': 'dummy 10'},
    {'name': 'dummy 11'},
    {'name': 'dummy 12'},
    {'name': 'dummy 13'},
    {'name': 'dummy 14'}
]
